#
# Using a single Consul host is _highly_ discouraged, but yolo
#
consul:
    image: progrium/consul:latest
    command: -server -bootstrap-expect 1 -ui-dir /ui
    mem_limit: 256m
    ports:
    - 53
    - 8300
    - 8301
    - 8302
    - 8400
    - 8500
    restart: always


# Manually bootstrap the first instance, then...
# Scale this tier and each additional container/instance will automatically
# self-configure as a member of the cluster
couchbase4:
    image: 0x74696d/triton-couchbase:4.0.0
    links:
    - consul
    mem_limit: 1g
    ports:
    - 8091
    - 8092
    - 11207
    - 11210
    - 11211
    - 18091
    - 18092
    restart: always

couchbase3:
    image: misterbisson/triton-couchbase
    links:
    - consul
    mem_limit: 1g
    ports:
    - 8091
    - 8092
    - 11207
    - 11210
    - 11211
    - 18091
    - 18092
    restart: always

benchmark_test:
    image: 0x74696d/cbc-benchmark-go
    mem_limit: 512m
    volumes:
    - ./test:/src
    links:
    - consul
    environment:
    - ITEMS=1000
    - GOPATH=/src/.godeps:/src
    command: /bin/bash
    restart: never

# run the client to create indexes. this client will exit when complete
benchmark_index:
    image: 0x74696d/cbc-benchmark
    mem_limit: 256m
    links:
    - consul
    environment:
    - ITEMS=1000000
    command: /bin/cbc-benchmark index
    restart: never

# run the client to load test data. this client will exit when complete
benchmark_load:
    image: 0x74696d/cbc-benchmark
    mem_limit: 256m
    links:
    - consul
    environment:
    - ITEMS=1000000
    command: /bin/cbc-benchmark load
    restart: never

# run the client to benchmark n1ql queries
benchmark_n1ql:
    image: 0x74696d/cbc-benchmark
    mem_limit: 256m
    links:
    - consul
    environment:
    - ITEMS=1000000
    - THREADS=1
    command: /bin/cbc-benchmark n1qlTest

# run the client to benchmark via pillowfight
benchmark_pillowfight:
    image: 0x74696d/cbc-benchmark
    mem_limit: 256m
    links:
    - consul
    environment:
    - ITEMS=1000000
    - THREADS=10
    command: /bin/cbc-benchmark pillowfight

# run the client to benchmark view queries
benchmark_views:
    image: 0x74696d/cbc-benchmark
    mem_limit: 256m
    links:
    - consul
    environment:
    - ITEMS=1000000
    - THREADS=10
    command: /bin/cbc-benchmark view
